### ISSUE TITLE
Show example of how to configure resource on concourse 0.76

### ISSUE THREAD

**Issue by zachgersh** [pivotal-cf-experimental/cloudformation-resource#3]
You can now deploy a resource be specifying `resource_types` in your `pipeline.yaml`

http://concourse.ci/configuring-resource-types.html

Could you please add an example of this to the README

**Comment by mmb** [comment]
We will look into updating this to the new way.

@mmb and @cbguder

**Comment by oozie** [comment]
Fixed in 8a63a1cb3830f3d2a11a364e69b5e1a82d100754
